# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: "9h@@_?tSufpC_5vAt$gjEf9VPJswNJgJ"

# Variables to accompany `group_vars/development/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  speedfitdating.laproducerguy.com:
    admin_password: "k%B2vnidV$6g*!bd"
    env:
      db_password: "!sD%TjXWnAP5MPp86H3a4^gm2eJ-jn7@"
